name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker build . --file Dockerfile.focal -t crate
      - run: docker run -d crate /bin/bash
      - run: npm install
      - run: npx @playwright/test install
      - run: npx playwright test -g "@Regression$"
      - run: docker cp crate:/playwright-report ./Reports
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: Reports