on:
  push:
    branches:
    - master

jobs:
  playwright-tests:
    runs-on: windows-latest # or windows-latest, ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # download code to github actions machine

      - uses: actions/setup-node@v2 # setup nodejs
        with:
         node-version: '14.1.0'

      - name: Install
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/playwright-container@v3.0.0
        uses: ianwalter/playwright-container@43940dfa7d309fe3569b9df407ae9e84dcbf2e7f
        with:
          args: npm ci
      - name: Test
        uses: ianwalter/playwright-container@43940dfa7d309fe3569b9df407ae9e84dcbf2e7f
        with:
          args: npx playwright test