name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.*
        cache: 'npm'
    - run: docker build . --file Dockerfile.focal -t plimage
    - run: docker run -d --name plcontainer plimage
    - run: sudo docker cp plcontainer:./tests/playwright_report /reports
	  - run: ls /reports
	  - uses: actions/upload-artifact@v2
      with:
        path: /reports