name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker-compose -f docker-compose.yml
      - run: docker-compose down
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: npm-test-results
          path: test-results