name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker-compose up
      - name: test
      - run: docker run --network container:playwright-test -s --retry 10 --retry-connrefused http://localhost:5000/
      - run: docker-compose down
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: npm-test-results
          path: test-results