name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: windows-latest
    container:
      image: mcr.microsoft.com/playwright:v1.25.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
