name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker build . --file Dockerfile.focal -t ganesh_2146
      - run: docker-compose down   
