name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker build . -d --file Dockerfile.focal --name crate
      - run: docker cp crate:/tests/playwright_report/ ./reports
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: ./reports