on:
  push:
    branches:
    - master

jobs:
 test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - name: Check out code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14.x'
      - name: Setup dependencies for playwright/browsers
        uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Push test report to artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30