name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: docker build . --file Dockerfile.focal -t plimage
      - run: docker run -d --name plcontainer plimage
      - run: docker exec -it plcontainer /bin/bash
      - run: npx playwright test -g "@Regression$"
      # - run: docker cp plcontainer:./tests/playwright_report /reports